### PR TITLE
Bugfixes, small additions, organization

### PR DESCRIPTION
**Pull request by ghost**
Small bugfix for hostname. Move idls to their own directory, since there's going to be more of these as time goes on. Add the two recently added idls to have their generated js version removed on clean.

### CODE REVIEW

**Comment by ghost** [comment]
There's some extra noise in these due to some automated removal of spaces at the end of lines. Let me know if you want me to remove that stuff or just leave it as is (removing end of line spaces is preferable due to a lot of stuff automatically doing it).

**Comment by davidflanagan** [comment]
Brandon,

Thanks for this pull request.  Lots of good stuff in here!  I commented on a couple of the individual commits, and would like you to address those before I merge.

I don't care much about the extra spaces at the end of lines.  But clearly your toolchain does.  The only problem I've got is that it makes it harder to find what has actually changed.  Do you have some way to remove extraneous spaces throughout the entire codebase?  So we can just do it once and then not have to deal with it again?  (Maybe I can find an emacs setting that will prevent me from adding extra spaces...)

Thanks

**Comment by ghost** [comment]
Yeah the whitespace thing is killing me. I'm trying to figure out which part of the process is causing that. I have it explicitly set to ignore whitespace in git but alas. I'll see if I can get it to stop doing that or if I can do a mass whitespace removal in one commit to keep that separate. I hadn't even noticed it was doing that until I made this pull.

**Comment by davidflanagan** [comment]
Thanks Brandon!

**Pull request merged**
